
    
=head1 NAME

Conf::Libconfig

=head1 FUNCTIONS




=head2 @func: config_destroy()

$ret = $config ->  config_destroy()

=over 4



=item @param: Conf::Libconfig::ConfigT $config




=item @ret: VOID




=item @since: 

=back







=head2 @func: config_get_auto_convert()

$ret = $config ->  config_get_auto_convert()

=over 4



=item @param: Conf::Libconfig::ConfigT $config




=item @ret: IV




=item @since: 

=back







=head2 @func: config_init()

$ret = $config ->  config_init()

=over 4



=item @param: Conf::Libconfig::ConfigT $config




=item @ret: VOID




=item @since: 

=back







=head2 @func: config_lookup()

$ret = $config ->  config_lookup($path)

=over 4



=item @param: Conf::Libconfig::ConfigT $config




=item @param: PV $path




=item @ret: Conf::Libconfig::ConfigSettingT




=item @since: 

=back







=head2 @func: config_lookup_bool()

$ret = $config ->  config_lookup_bool($path,$value)

=over 4



=item @param: Conf::Libconfig::ConfigT $config




=item @param: PV $path




=item @param: PTR $value




=item @ret: IV




=item @since: 

=back







=head2 @func: config_lookup_float()

$ret = $config ->  config_lookup_float($path,$value)

=over 4



=item @param: Conf::Libconfig::ConfigT $config




=item @param: PV $path




=item @param: PTR $value




=item @ret: IV




=item @since: 

=back







=head2 @func: config_lookup_int()

$ret = $config ->  config_lookup_int($path,$value)

=over 4



=item @param: Conf::Libconfig::ConfigT $config




=item @param: PV $path




=item @param: PTR $value




=item @ret: IV




=item @since: 

=back







=head2 @func: config_lookup_int64()

$ret = $config ->  config_lookup_int64($path,$value)

=over 4



=item @param: Conf::Libconfig::ConfigT $config




=item @param: PV $path




=item @param: PTR $value




=item @ret: IV




=item @since: 

=back







=head2 @func: config_read()

$ret = $config ->  config_read($stream)

=over 4



=item @param: Conf::Libconfig::ConfigT $config




=item @param: PV $stream




=item @ret: IV




=item @since: 

=back







=head2 @func: config_read_file()

$ret = $config ->  config_read_file($filename)

=over 4



=item @param: Conf::Libconfig::ConfigT $config




=item @param: PV $filename




=item @ret: IV




=item @since: 

=back







=head2 @func: config_set_auto_convert()

$ret = $config ->  config_set_auto_convert($flag)

=over 4



=item @param: Conf::Libconfig::ConfigT $config




=item @param: IV $flag




=item @ret: VOID




=item @since: 

=back







=head2 @func: config_setting_add()

$ret = $parent ->  config_setting_add($name,$type)

=over 4



=item @param: Conf::Libconfig::ConfigSettingT $parent




=item @param: PV $name




=item @param: IV $type




=item @ret: Conf::Libconfig::ConfigSettingT




=item @since: 

=back







=head2 @func: config_setting_get_bool()

$ret = $setting ->  config_setting_get_bool()

=over 4



=item @param: Conf::Libconfig::ConfigSettingT $setting




=item @ret: IV




=item @since: 

=back







=head2 @func: config_setting_get_bool_elem()

$ret = $setting ->  config_setting_get_bool_elem($idx)

=over 4



=item @param: Conf::Libconfig::ConfigSettingT $setting




=item @param: IV $idx




=item @ret: IV




=item @since: 

=back







=head2 @func: config_setting_get_elem()

$ret = $setting ->  config_setting_get_elem($idx)

=over 4



=item @param: Conf::Libconfig::ConfigSettingT $setting




=item @param: UV $idx




=item @ret: Conf::Libconfig::ConfigSettingT




=item @since: 

=back







=head2 @func: config_setting_get_float()

$ret = $setting ->  config_setting_get_float()

=over 4



=item @param: Conf::Libconfig::ConfigSettingT $setting




=item @ret: NV




=item @since: 

=back







=head2 @func: config_setting_get_float_elem()

$ret = $setting ->  config_setting_get_float_elem($idx)

=over 4



=item @param: Conf::Libconfig::ConfigSettingT $setting




=item @param: IV $idx




=item @ret: NV




=item @since: 

=back







=head2 @func: config_setting_get_format()

$ret = $setting ->  config_setting_get_format()

=over 4



=item @param: Conf::Libconfig::ConfigSettingT $setting




=item @ret: IV




=item @since: 

=back







=head2 @func: config_setting_get_int()

$ret = $setting ->  config_setting_get_int()

=over 4



=item @param: Conf::Libconfig::ConfigSettingT $setting




=item @ret: IV




=item @since: 

=back







=head2 @func: config_setting_get_int64()

$ret = $setting ->  config_setting_get_int64()

=over 4



=item @param: Conf::Libconfig::ConfigSettingT $setting




=item @ret: IV




=item @since: 

=back







=head2 @func: config_setting_get_int64_elem()

$ret = $setting ->  config_setting_get_int64_elem($idx)

=over 4



=item @param: Conf::Libconfig::ConfigSettingT $setting




=item @param: IV $idx




=item @ret: IV




=item @since: 

=back







=head2 @func: config_setting_get_int_elem()

$ret = $setting ->  config_setting_get_int_elem($idx)

=over 4



=item @param: Conf::Libconfig::ConfigSettingT $setting




=item @param: IV $idx




=item @ret: IV




=item @since: 

=back







=head2 @func: config_setting_get_member()

$ret = $setting ->  config_setting_get_member($name)

=over 4



=item @param: Conf::Libconfig::ConfigSettingT $setting




=item @param: PV $name




=item @ret: Conf::Libconfig::ConfigSettingT




=item @since: 

=back







=head2 @func: config_setting_get_string()

$ret = $setting ->  config_setting_get_string()

=over 4



=item @param: Conf::Libconfig::ConfigSettingT $setting




=item @ret: PV




=item @since: 

=back







=head2 @func: config_setting_get_string_elem()

$ret = $setting ->  config_setting_get_string_elem($idx)

=over 4



=item @param: Conf::Libconfig::ConfigSettingT $setting




=item @param: IV $idx




=item @ret: PV




=item @since: 

=back







=head2 @func: config_setting_index()

$ret = $setting ->  config_setting_index()

=over 4



=item @param: Conf::Libconfig::ConfigSettingT $setting




=item @ret: IV




=item @since: 

=back







=head2 @func: config_setting_length()

$ret = $setting ->  config_setting_length()

=over 4



=item @param: Conf::Libconfig::ConfigSettingT $setting




=item @ret: IV




=item @since: 

=back







=head2 @func: config_setting_lookup_bool()

$ret = $setting ->  config_setting_lookup_bool($name,$value)

=over 4



=item @param: Conf::Libconfig::ConfigSettingT $setting




=item @param: PV $name




=item @param: PTR $value




=item @ret: IV




=item @since: 

=back







=head2 @func: config_setting_lookup_float()

$ret = $setting ->  config_setting_lookup_float($name,$value)

=over 4



=item @param: Conf::Libconfig::ConfigSettingT $setting




=item @param: PV $name




=item @param: PTR $value




=item @ret: IV




=item @since: 

=back







=head2 @func: config_setting_lookup_int()

$ret = $setting ->  config_setting_lookup_int($name,$value)

=over 4



=item @param: Conf::Libconfig::ConfigSettingT $setting




=item @param: PV $name




=item @param: PTR $value




=item @ret: IV




=item @since: 

=back







=head2 @func: config_setting_lookup_int64()

$ret = $setting ->  config_setting_lookup_int64($name,$value)

=over 4



=item @param: Conf::Libconfig::ConfigSettingT $setting




=item @param: PV $name




=item @param: PTR $value




=item @ret: IV




=item @since: 

=back







=head2 @func: config_setting_remove()

$ret = $parent ->  config_setting_remove($name)

=over 4



=item @param: Conf::Libconfig::ConfigSettingT $parent




=item @param: PV $name




=item @ret: IV




=item @since: 

=back







=head2 @func: config_setting_remove_elem()

$ret = $parent ->  config_setting_remove_elem($idx)

=over 4



=item @param: Conf::Libconfig::ConfigSettingT $parent




=item @param: UV $idx




=item @ret: IV




=item @since: 

=back







=head2 @func: config_setting_set_bool()

$ret = $setting ->  config_setting_set_bool($value)

=over 4



=item @param: Conf::Libconfig::ConfigSettingT $setting




=item @param: IV $value




=item @ret: IV




=item @since: 

=back







=head2 @func: config_setting_set_bool_elem()

$ret = $setting ->  config_setting_set_bool_elem($idx,$value)

=over 4



=item @param: Conf::Libconfig::ConfigSettingT $setting




=item @param: IV $idx




=item @param: IV $value




=item @ret: Conf::Libconfig::ConfigSettingT




=item @since: 

=back







=head2 @func: config_setting_set_float()

$ret = $setting ->  config_setting_set_float($value)

=over 4



=item @param: Conf::Libconfig::ConfigSettingT $setting




=item @param: NV $value




=item @ret: IV




=item @since: 

=back







=head2 @func: config_setting_set_float_elem()

$ret = $setting ->  config_setting_set_float_elem($idx,$value)

=over 4



=item @param: Conf::Libconfig::ConfigSettingT $setting




=item @param: IV $idx




=item @param: NV $value




=item @ret: Conf::Libconfig::ConfigSettingT




=item @since: 

=back







=head2 @func: config_setting_set_format()

$ret = $setting ->  config_setting_set_format($format)

=over 4



=item @param: Conf::Libconfig::ConfigSettingT $setting




=item @param: IV $format




=item @ret: IV




=item @since: 

=back







=head2 @func: config_setting_set_hook()

$ret = $setting ->  config_setting_set_hook($hook)

=over 4



=item @param: Conf::Libconfig::ConfigSettingT $setting




=item @param: PTR $hook




=item @ret: VOID




=item @since: 

=back







=head2 @func: config_setting_set_int()

$ret = $setting ->  config_setting_set_int($value)

=over 4



=item @param: Conf::Libconfig::ConfigSettingT $setting




=item @param: IV $value




=item @ret: IV




=item @since: 

=back







=head2 @func: config_setting_set_int64()

$ret = $setting ->  config_setting_set_int64($value)

=over 4



=item @param: Conf::Libconfig::ConfigSettingT $setting




=item @param: IV $value




=item @ret: IV




=item @since: 

=back







=head2 @func: config_setting_set_int64_elem()

$ret = $setting ->  config_setting_set_int64_elem($idx,$value)

=over 4



=item @param: Conf::Libconfig::ConfigSettingT $setting




=item @param: IV $idx




=item @param: IV $value




=item @ret: Conf::Libconfig::ConfigSettingT




=item @since: 

=back







=head2 @func: config_setting_set_int_elem()

$ret = $setting ->  config_setting_set_int_elem($idx,$value)

=over 4



=item @param: Conf::Libconfig::ConfigSettingT $setting




=item @param: IV $idx




=item @param: IV $value




=item @ret: Conf::Libconfig::ConfigSettingT




=item @since: 

=back







=head2 @func: config_setting_set_string()

$ret = $setting ->  config_setting_set_string($value)

=over 4



=item @param: Conf::Libconfig::ConfigSettingT $setting




=item @param: PV $value




=item @ret: IV




=item @since: 

=back







=head2 @func: config_setting_set_string_elem()

$ret = $setting ->  config_setting_set_string_elem($idx,$value)

=over 4



=item @param: Conf::Libconfig::ConfigSettingT $setting




=item @param: IV $idx




=item @param: PV $value




=item @ret: Conf::Libconfig::ConfigSettingT




=item @since: 

=back







=head2 @func: config_write()

$ret = $config ->  config_write($stream)

=over 4



=item @param: Conf::Libconfig::ConfigT $config




=item @param: PV $stream




=item @ret: VOID




=item @since: 

=back







=head2 @func: config_write_file()

$ret = $config ->  config_write_file($filename)

=over 4



=item @param: Conf::Libconfig::ConfigT $config




=item @param: PV $filename




=item @ret: IV




=item @since: 

=back







=head2 @func: yyalloc()

$ret =  yyalloc($arg0,$yyscanner)

=over 4



=item @param: UV $arg0




=item @param: PTR $yyscanner




=item @ret: PTR




=item @since: 

=back







=head2 @func: yyfree()

 yyfree($arg0,$yyscanner)

=over 4



=item @param: PTR $arg0




=item @param: PTR $yyscanner




=item @since: 

=back







=head2 @func: yyget_debug()

$ret =  yyget_debug($yyscanner)

=over 4



=item @param: PTR $yyscanner




=item @ret: IV




=item @since: 

=back







=head2 @func: yyget_extra()

$ret =  yyget_extra($yyscanner)

=over 4



=item @param: PTR $yyscanner




=item @ret: PTR




=item @since: 

=back







=head2 @func: yyget_in()

$ret =  yyget_in($yyscanner)

=over 4



=item @param: PTR $yyscanner




=item @ret: PV




=item @since: 

=back







=head2 @func: yyget_leng()

$ret =  yyget_leng($yyscanner)

=over 4



=item @param: PTR $yyscanner




=item @ret: IV




=item @since: 

=back







=head2 @func: yyget_lineno()

$ret =  yyget_lineno($yyscanner)

=over 4



=item @param: PTR $yyscanner




=item @ret: IV




=item @since: 

=back







=head2 @func: yyget_out()

$ret =  yyget_out($yyscanner)

=over 4



=item @param: PTR $yyscanner




=item @ret: PV




=item @since: 

=back







=head2 @func: yylex_destroy()

$ret =  yylex_destroy($yyscanner)

=over 4



=item @param: PTR $yyscanner




=item @ret: IV




=item @since: 

=back







=head2 @func: yylex_init()

$ret =  yylex_init($scanner)

=over 4



=item @param: PTR $scanner




=item @ret: IV




=item @since: 

=back







=head2 @func: yypop_buffer_state()

 yypop_buffer_state($yyscanner)

=over 4



=item @param: PTR $yyscanner




=item @since: 

=back







=head2 @func: yyrealloc()

$ret =  yyrealloc($arg0,$arg1,$yyscanner)

=over 4



=item @param: PTR $arg0




=item @param: UV $arg1




=item @param: PTR $yyscanner




=item @ret: PTR




=item @since: 

=back







=head2 @func: yyrestart()

 yyrestart($input_file,$yyscanner)

=over 4



=item @param: PV $input_file




=item @param: PTR $yyscanner




=item @since: 

=back







=head2 @func: yyset_debug()

 yyset_debug($debug_flag,$yyscanner)

=over 4



=item @param: IV $debug_flag




=item @param: PTR $yyscanner




=item @since: 

=back







=head2 @func: yyset_extra()

 yyset_extra($user_defined,$yyscanner)

=over 4



=item @param: PTR $user_defined




=item @param: PTR $yyscanner




=item @since: 

=back







=head2 @func: yyset_in()

 yyset_in($in_str,$yyscanner)

=over 4



=item @param: PV $in_str




=item @param: PTR $yyscanner




=item @since: 

=back







=head2 @func: yyset_lineno()

 yyset_lineno($line_number,$yyscanner)

=over 4



=item @param: IV $line_number




=item @param: PTR $yyscanner




=item @since: 

=back







=head2 @func: yyset_out()

 yyset_out($out_str,$yyscanner)

=over 4



=item @param: PV $out_str




=item @param: PTR $yyscanner




=item @since: 

=back







=head2 @func: yywrap()

$ret =  yywrap($yyscanner)

=over 4



=item @param: PTR $yyscanner




=item @ret: IV




=item @since: 

=back





