# 
# /*
#  * *********** WARNING **************
#  * This file generated by Conf::Libconfig::WrapXS/0.001
#  * Any changes made here will be lost
#  * ***********************************
#  * 1. /usr/lib/perl5/vendor_perl/5.10.0/ExtUtils/XSBuilder/WrapXS.pm:52
#  * 2. /usr/lib/perl5/vendor_perl/5.10.0/ExtUtils/XSBuilder/WrapXS.pm:2068
#  * 3. ./bin/WrapXSRun.pl:10
#  */
# 


package Conf::Libconfig::ConfigSettingT;
require DynaLoader ;
use strict ;
use vars qw{$VERSION @ISA} ;

push @ISA, 'DynaLoader' ;
$VERSION = '0.01';
bootstrap Conf::Libconfig::ConfigSettingT $VERSION ;



1;
__END__
