
    
=head1 NAME

Conf::Libconfig::ConfigSettingT

=head1 FUNCTIONS




=head2 @func: type()

$val = $obj -> type($newval)

=over 4

=item @param: Conf::Libconfig::ConfigSettingT $obj

=item @param: IV $newval


=back







=head2 @func: format()

$val = $obj -> format($newval)

=over 4

=item @param: Conf::Libconfig::ConfigSettingT $obj

=item @param: IV $newval


=back







=head2 @func: value()

$val = $obj -> value($newval)

=over 4

=item @param: Conf::Libconfig::ConfigSettingT $obj

=item @param: Conf::Libconfig::ConfigValueT $newval


=back







=head2 @func: parent()

$val = $obj -> parent($newval)

=over 4

=item @param: Conf::Libconfig::ConfigSettingT $obj

=item @param: Conf::Libconfig::ConfigSettingT $newval


=back







=head2 @func: config()

$val = $obj -> config($newval)

=over 4

=item @param: Conf::Libconfig::ConfigSettingT $obj

=item @param: Conf::Libconfig::ConfigT $newval


=back







=head2 @func: hook()

$val = $obj -> hook($newval)

=over 4

=item @param: Conf::Libconfig::ConfigSettingT $obj

=item @param: PTR $newval


=back







=head2 @func: line()

$val = $obj -> line($newval)

=over 4

=item @param: Conf::Libconfig::ConfigSettingT $obj

=item @param: UV $newval


=back





