#
#   - Conf-Libconfig -
#   This spec file was automatically generated by cpan2rpm [ver: 2.029]
#   The following arguments were used:
#       Conf-Libconfig-0.08.tar.gz
#   For more information on cpan2rpm please visit: http://perl.arix.com/
#
%define _tmppath %{_topdir}/BUILDROOT
%define pkgname Conf-Libconfig
%define filelist %{pkgname}-%{version}-filelist
%define NVR %{pkgname}-%{version}-%{release}
%define maketest 1

name:      perl-Conf-Libconfig
summary:   Conf-Libconfig - Perl extension for libconfig
version:   1.0.3
release:   1%{?dist}
vendor:    Cnangel <cnangel@gmail.com>
packager:  Cnangel <cnangel@gmail.com>
license:   Artistic
group:     Applications/CPAN
url:       https://github.com/cnangel/Conf-Libconfig
buildroot: %{_tmppath}/%{name}-%{version}-%(id -u -n)
buildarch: x86_64
prefix:    %{_prefix}
source:    %{name}-%{version}.tar.gz
BuildRequires: perl-bignum gcc perl-CPAN
BuildRequires: perl(Test::Deep) perl(Test::Warn) perl(Test::Exception) perl(ExtUtils::PkgConfig)

%description
You can use `Conf::Libconfig' for perl config, and support Scalar, Array and Hash data structures etc.
like C or C++ function. `Conf::Libconfig' could reduce your config file and quote by C/C++ transportability.

#
# This package was generated automatically with the cpan2rpm
# utility.  To get this software or for more information
# please visit: http://perl.arix.com/
#

%prep
%setup -q

%build
perl Makefile.PL INSTALLDIRS=vendor NO_PACKLIST=1 NO_PERLLOCAL=1
%{make_build}

%check
%if %maketest
%{__make} test
%endif

%install
rm -rf %{buildroot}
%{make_install}


%clean
[ "%{buildroot}" != "/" ] && rm -rf %{buildroot}

%files
%defattr(-,root,root)
%doc Changes.md README.md
%{perl_archlib}/*
%{_mandir}/man3/*

%changelog
* Sun Sep 03 2023 Cnangel <cnangel@gmail.com> 1.0.3-1
- Fix some issues.
* Sun Mar 19 2023 Cnangel <cnangel@gmail.com> 1.0.0-1
- Upgrade version 1.0.0
* Sun Mar 19 2023 Cnangel <cnangel@gmail.com> 0.200-1
- Update general value.
* Sun May 29 2022 Cnangel <cnangel@gmail.com> 0.101-1
- Update for libconfig-1.7.3
* Mon Aug 5 2013 cnangel@localhost.localdomain
- Initial build.
