
    
=head1 NAME

Conf::Libconfig::ConfigListT

=head1 FUNCTIONS




=head2 @func: length()

$val = $obj -> length($newval)

=over 4

=item @param: Conf::Libconfig::ConfigListT $obj

=item @param: UV $newval


=back







=head2 @func: capacity()

$val = $obj -> capacity($newval)

=over 4

=item @param: Conf::Libconfig::ConfigListT $obj

=item @param: UV $newval


=back





