package Conf::Libconfig::CallbackTable;

# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# ! WARNING: generated by Conf::Libconfig::ParseSource/0.001
# !          Tue Jun 30 15:11:46 2009
# !          do NOT edit, any changes will be lost !
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

$Conf::Libconfig::CallbackTable = [];


1;
