package Conf::Libconfig::StructureTable;

# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# ! WARNING: generated by Conf::Libconfig::ParseSource/0.001
# !          Tue Jun 30 15:11:46 2009
# !          do NOT edit, any changes will be lost !
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

$Conf::Libconfig::StructureTable = [
  {
    'type' => 'config_list_t',
    'stype' => 'struct config_list_t',
    'elts' => [
      {
        'type' => 'unsigned int',
        'name' => 'length'
      },
      {
        'type' => 'unsigned int',
        'name' => 'capacity'
      },
      {
        'type' => 'config_setting_t * *',
        'name' => 'elements'
      }
    ]
  },
  {
    'type' => 'config_setting_t',
    'stype' => 'struct config_setting_t',
    'elts' => [
      {
        'type' => 'char *',
        'name' => 'name'
      },
      {
        'type' => 'short',
        'name' => 'type'
      },
      {
        'type' => 'short',
        'name' => 'format'
      },
      {
        'type' => 'config_value_t',
        'name' => 'value'
      },
      {
        'type' => 'struct config_setting_t *',
        'name' => 'parent'
      },
      {
        'type' => 'struct config_t *',
        'name' => 'config'
      },
      {
        'type' => 'void *',
        'name' => 'hook'
      },
      {
        'type' => 'unsigned int',
        'name' => 'line'
      }
    ]
  },
  {
    'type' => 'struct parse_context',
    'stype' => 'struct parse_context',
    'elts' => [
      {
        'type' => 'config_t *',
        'name' => 'config'
      },
      {
        'type' => 'config_setting_t *',
        'name' => 'parent'
      },
      {
        'type' => 'config_setting_t *',
        'name' => 'setting'
      },
      {
        'type' => 'char *',
        'name' => 'name'
      }
    ]
  }
];


1;
