/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.18_02 from the
 * contents of ConfigListT.xs. Do not edit this file, edit ConfigListT.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "ConfigListT.xs"

/*
 * *********** WARNING **************
 * This file generated by Conf::Libconfig::WrapXS/0.001
 * Any changes made here will be lost
 * ***********************************
 * 1. /usr/lib/perl5/vendor_perl/5.10.0/ExtUtils/XSBuilder/WrapXS.pm:52
 * 2. /usr/lib/perl5/vendor_perl/5.10.0/ExtUtils/XSBuilder/WrapXS.pm:2068
 * 3. ./bin/WrapXSRun.pl:10
 */


#include "/media/ext4/src/src/Conf-Libconfig/src/wincompat.h"

#include "/media/ext4/src/src/Conf-Libconfig/src/scanner.h"

#include "/media/ext4/src/src/Conf-Libconfig/src/grammar.h"

#include "/media/ext4/src/src/Conf-Libconfig/src/private.h"

#include "/media/ext4/src/src/Conf-Libconfig/src/libconfig.h"

#include "EXTERN.h"

#include "perl.h"

#include "XSUB.h"

#include "libconfig_xs_sv_convert.h"

#include "libconfig_xs_typedefs.h"



void Conf__Libconfig__ConfigListT_new_init (pTHX_ Conf__Libconfig__ConfigListT  obj, SV * item, int overwrite) {

    SV * * tmpsv ;

    if (SvTYPE(item) == SVt_PVMG) 
        memcpy (obj, (void *)SvIVX(item), sizeof (*obj)) ;
    else if (SvTYPE(item) == SVt_PVHV) {
        if ((tmpsv = hv_fetch((HV *)item, "length", sizeof("length") - 1, 0)) || overwrite) {
            obj -> length = (unsigned int)config_xs_sv2_UV((tmpsv && *tmpsv?*tmpsv:&PL_sv_undef)) ;
        }
        if ((tmpsv = hv_fetch((HV *)item, "capacity", sizeof("capacity") - 1, 0)) || overwrite) {
            obj -> capacity = (unsigned int)config_xs_sv2_UV((tmpsv && *tmpsv?*tmpsv:&PL_sv_undef)) ;
        }
   ; }

    else
        croak ("initializer for Conf::Libconfig::ConfigListT::new is not a hash or object reference") ;

} ;


#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#line 70 "ConfigListT.c"

XS(XS_Conf__Libconfig__ConfigListT_length); /* prototype to pass -Wmissing-prototypes */
XS(XS_Conf__Libconfig__ConfigListT_length)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 1 || items > 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Conf::Libconfig::ConfigListT::length", "obj, val=0");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Conf__Libconfig__ConfigListT	obj;
	unsigned int	val;
#line 63 "ConfigListT.xs"
    /*nada*/

#line 89 "ConfigListT.c"
	unsigned int	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "Conf::Libconfig::ConfigListT")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    obj = INT2PTR(Conf__Libconfig__ConfigListT,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"Conf::Libconfig::ConfigListT::length",
			"obj", "Conf::Libconfig::ConfigListT");

	if (items < 2)
	    val = 0;
	else {
	    val = (unsigned int)SvUV(ST(1));
	}
#line 66 "ConfigListT.xs"
    RETVAL = (unsigned int)  obj->length;

    if (items > 1) {
        obj->length = (unsigned int) val;
    }
#line 113 "ConfigListT.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Conf__Libconfig__ConfigListT_capacity); /* prototype to pass -Wmissing-prototypes */
XS(XS_Conf__Libconfig__ConfigListT_capacity)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 1 || items > 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Conf::Libconfig::ConfigListT::capacity", "obj, val=0");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Conf__Libconfig__ConfigListT	obj;
	unsigned int	val;
#line 81 "ConfigListT.xs"
    /*nada*/

#line 137 "ConfigListT.c"
	unsigned int	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "Conf::Libconfig::ConfigListT")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    obj = INT2PTR(Conf__Libconfig__ConfigListT,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"Conf::Libconfig::ConfigListT::capacity",
			"obj", "Conf::Libconfig::ConfigListT");

	if (items < 2)
	    val = 0;
	else {
	    val = (unsigned int)SvUV(ST(1));
	}
#line 84 "ConfigListT.xs"
    RETVAL = (unsigned int)  obj->capacity;

    if (items > 1) {
        obj->capacity = (unsigned int) val;
    }
#line 161 "ConfigListT.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Conf__Libconfig__ConfigListT_new); /* prototype to pass -Wmissing-prototypes */
XS(XS_Conf__Libconfig__ConfigListT_new)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 1 || items > 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Conf::Libconfig::ConfigListT::new", "class, initializer=NULL");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	char *	class = (char *)SvPV_nolen(ST(0));
	SV *	initializer;
#line 101 "ConfigListT.xs"
    SV * svobj ;
    Conf__Libconfig__ConfigListT  cobj ;
    SV * tmpsv ;
#line 186 "ConfigListT.c"
	SV *	RETVAL;

	if (items < 2)
	    initializer = NULL;
	else {
	    initializer = ST(1);
	}
#line 105 "ConfigListT.xs"
    config_xs_Conf__Libconfig__ConfigListT_create_obj(cobj,svobj,RETVAL,malloc(sizeof(*cobj))) ;

    if (initializer) {
        if (!SvROK(initializer) || !(tmpsv = SvRV(initializer))) 
            croak ("initializer for Conf::Libconfig::ConfigListT::new is not a reference") ;

        if (SvTYPE(tmpsv) == SVt_PVHV || SvTYPE(tmpsv) == SVt_PVMG)  
            Conf__Libconfig__ConfigListT_new_init (aTHX_ cobj, tmpsv, 0) ;
        else if (SvTYPE(tmpsv) == SVt_PVAV) {
            int i ;
            SvGROW(svobj, sizeof (*cobj) * av_len((AV *)tmpsv)) ;     
            for (i = 0; i <= av_len((AV *)tmpsv); i++) {
                SV * * itemrv = av_fetch((AV *)tmpsv, i, 0) ;
                SV * item ;
                if (!itemrv || !*itemrv || !SvROK(*itemrv) || !(item = SvRV(*itemrv))) 
                    croak ("array element of initializer for Conf::Libconfig::ConfigListT::new is not a reference") ;
                Conf__Libconfig__ConfigListT_new_init (aTHX_ &cobj[i], item, 1) ;
            }
        }
        else {
             croak ("initializer for Conf::Libconfig::ConfigListT::new is not a hash/array/object reference") ;
        }
    }
#line 218 "ConfigListT.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Conf__Libconfig__ConfigListT); /* prototype to pass -Wmissing-prototypes */
XS(boot_Conf__Libconfig__ConfigListT)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    char* file = __FILE__;

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXS("Conf::Libconfig::ConfigListT::length", XS_Conf__Libconfig__ConfigListT_length, file);
        newXS("Conf::Libconfig::ConfigListT::capacity", XS_Conf__Libconfig__ConfigListT_capacity, file);
        newXS("Conf::Libconfig::ConfigListT::new", XS_Conf__Libconfig__ConfigListT_new, file);

    /* Initialisation Section */

#line 134 "ConfigListT.xs"
    items = items; /* -Wall */

#line 251 "ConfigListT.c"

    /* End of Initialisation Section */

    if (PL_unitcheckav)
         call_list(PL_scopestack_ix, PL_unitcheckav);
    XSRETURN_YES;
}

