
/*
 * *********** WARNING **************
 * This file generated by Conf::Libconfig::WrapXS/0.001
 * Any changes made here will be lost
 * ***********************************
 * 1. /usr/lib/perl5/vendor_perl/5.10.0/ExtUtils/XSBuilder/WrapXS.pm:52
 * 2. /usr/lib/perl5/vendor_perl/5.10.0/ExtUtils/XSBuilder/WrapXS.pm:2068
 * 3. ./bin/WrapXSRun.pl:10
 */


#ifndef LIBCONFIG_XS_TYPEDEFS_H
#define LIBCONFIG_XS_TYPEDEFS_H

typedef yy_buffer_state * Conf__Libconfig__YYBufferState;
typedef config_list_t * Conf__Libconfig__ConfigListT;
typedef config_setting_t * Conf__Libconfig__ConfigSettingT;
typedef config_t * Conf__Libconfig__ConfigT;
typedef parse_context * Conf__Libconfig__ParseContext;
typedef void * PTR;
#if PERL_VERSION > 5
typedef char * PV;
#endif
typedef char * PVnull;

#ifndef pTHX_
#define pTHX_
#endif
#ifndef aTHX_
#define aTHX_
#endif
#ifndef pTHX
#define pTHX
#endif
#ifndef aTHX
#define aTHX
#endif

#ifndef XSprePUSH
#define XSprePUSH (sp = PL_stack_base + ax - 1)
#endif


#endif /* LIBCONFIG_XS_TYPEDEFS_H */
