
    
=head1 NAME

Conf::Libconfig::ParseContext

=head1 FUNCTIONS




=head2 @func: config()

$val = $obj -> config($newval)

=over 4

=item @param: Conf::Libconfig::ParseContext $obj

=item @param: Conf::Libconfig::ConfigT $newval


=back







=head2 @func: parent()

$val = $obj -> parent($newval)

=over 4

=item @param: Conf::Libconfig::ParseContext $obj

=item @param: Conf::Libconfig::ConfigSettingT $newval


=back







=head2 @func: setting()

$val = $obj -> setting($newval)

=over 4

=item @param: Conf::Libconfig::ParseContext $obj

=item @param: Conf::Libconfig::ConfigSettingT $newval


=back





