---
name: test

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"
  pull_request:
  workflow_dispatch:

jobs:
  perls:
    name: "Linux with Perl ${{ matrix.perl-version }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - "devel"
          - "5.38"
          - "5.36"
          - "5.34"
          - "5.32"
          - "5.30"
          - "5.28"
          - "5.26"
          - "5.24"
          - "5.22"
          - "5.20"
          - "5.18"
          - "5.16"
          - "5.14"
          - "5.12"
          - "5.10"
          - "5.8"
    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: |
          perl --version
          apt-get -y install libconfig-dev
          perl Makefile.PL
          make
          make test
          make install
# vi:set et ts=2 sw=2:
